### ISSUE TITLE
American english aliases for methods

### ISSUE THREAD

**Issue by djsegal** [JuliaIntervals/IntervalOptimisation.jl#1]
For us uncivilized folk in the north, `minimise` and `maximise` might prove to be confusing

**Comment by dpsanders** [comment]
Yes, I guess there should be aliases.

**Comment by dpsanders** [comment]
Fixed in master.

**Comment by djsegal** [comment]
Textbook American imperialism

**Comment by dpsanders** [comment]
Tab completion is, of course, now actually *worse* than before. Maybe I should take the aliases out again...

**Comment by djsegal** [comment]
Probably not the worst thing. At least you have a good reason against it now
