### ISSUE TITLE
SortedVector.jl is not giving correct result.

### ISSUE THREAD

**Issue by yashcodes** [JuliaIntervals/IntervalOptimisation.jl#18]

**Comment by yashcodes** [comment]
""julia> working=SortedVector([(X,2),(Y,1)],x->x[2]);working.data
2-element Array{Tuple{Interval{Float64},Int64},1}:
 ([1, 2], 2)
 ([2, 3], 1)
""
as we can see the order of vector is not correct.

**Comment by yashcodes** [comment]
In SortedVector.jl if we modify 
''new{T,F}(sort(data), by)" to " new{T,F}(sort(data,by), by)"
it will start giving correct result.

**Comment by yashcodes** [comment]
""julia> working=SortedVector([(X,2),(Y,1)],x->x[2]);working.data
2-element Array{Tuple{Interval{Float64},Int64},1}:
([2, 3], 1)
([1, 2], 2)
""

**Comment by dpsanders** [comment]
Please comment code using three backticks:  ```
