### ISSUE TITLE
Doc link is broken

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaIntervals/IntervalOptimisation.jl#3]
I am not quite sure what's wrong with it: the url looks correct.

**Comment by dpsanders** [comment]
What's wrong is that the docs consist of the empty set... The only docs are in the readme.

**Comment by dpsanders** [comment]
:/

**Comment by DNF2** [comment]
I was just confused by this, and spent a couple of minutes. Maybe remove the broken link?

**Comment by dpsanders** [comment]
Or make some proper docs. Cc @yashcodes.

Thanks for reminding me about this.
