### ISSUE TITLE
HeapedVector sorting?

### ISSUE THREAD

**Issue by braamvandyk** [JuliaIntervals/IntervalOptimisation.jl#34]
Not sure if this is a real issue.

Is a HeapedVector meant to be sorted? I gathered so from the code, specifically the call to floatup!(). If so, then there is a bug in floatup!(). If not, then please disregard the rest of this.

## Example:

```
julia> v = collect(1:2:19); insert!(v, length(v)+1, 4)
11-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11
 13
 15
 17
 19
  4

julia> floatup!(v, length(v), identity)
11-element Array{Int64,1}:
  1
  3
  5
  7
  4
 11
 13
 15
 17
 19
  9
```
The example is based on my understanding that when a HeapedVector is created, the data is added one value at a time (obviously intervals, but this is easier to demo with floats) and floatup!() will then sort the newly added value into the existing set.

The error (if this is an error - see above) stems from the line

```
par = convert(Int, floor(index/2))
```
## Proposal:

I would propose a correction, which works, but is not especially efficient:

```
function floatup2!(ar, index, by)
    if index <= 1
        return ar
    else    
        par = index - 1
    end
    if by(ar[index]) < by(ar[par])
       ar[par], ar[index] = ar[index], ar[par]
    end
    floatup2!(ar, par, by)
end
```

This sorts as expected:

```
julia> v = collect(1:2:19); insert!(v, length(v)+1, 4)
11-element Array{Int64,1}:
  1
  3
  5
  7
  9
 11
 13
 15
 17
 19
  4

julia> floatup2!(v, length(v), identity)
11-element Array{Int64,1}:
  1
  3
  4
  5
  7
  9
 11
 13
 15
 17
 19
```

**Comment by dpsanders** [comment]
Thanks for the question and very sorry that for some reason I didn't see this.

A `HeapedVector` is supposed to have the structure of a binary heap, so the entries will not be sorted in the usual order inside the vector.

In any case this will probably be removed soon.
